import type { NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios'
import { Video } from '../types'
import NoResults from '../components/NoResults'
import VideoCard from '../components/VideoCard'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

interface IProps {
  videos: Video[]
}

const Home /* NextPage */ = ({ videos } : IProps) => {
  // console.log(videos)
  return (
    <div className="flex flex-col gap-10 videos h-full">
      <Head>
        <title>Blektik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
           videos.length ? (
            videos.map((video: Video, index) => (
              <VideoCard post={video} key={index}/>
            ))
           ) : (
            <NoResults text={'No Videos'} />
           )
      }


    </div>
  )
}


export const getServerSideProps = async () => {
  const response = await axios.get(`http://localhost:3000/api/posts`)

  const { data } = response

  // console.log(data)
  return {
    props : {
      videos: data
    }
  }
}

export default Home
